version: "3.3"
services:
  db:
    container_name: mysql-server-db
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ONETIME_PASSWORD: 'false'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'hooman'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      # - type: volume
      #   source: $HOST/location
      #   target: /container/location
      - type: bind
        source: /home/hooman/workSpace/mysql_database
        target: /var/lib/mysql
      # - my-db:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    
# Names our volume
volumes:
    my-db:

